controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

signup:
    path: /signup
    controller: App\Controller\SecurityController::signup

